### ISSUE TITLE
doc: add documentation for manual testing

### ISSUE THREAD

**Issue by findleyr** [govim/govim#749]
It took a bit of digging through the source to find that I could set `GOVIM_RUNCMD` to test running govim against a locally modified version of the govim binary, and then a bit longer to realize that this required absolute paths (so `export GOVIM_RUNCMD="$(which govim) $(which gopls)` is a nice trick).  

Perhaps my workflow is nonstandard, and I should be modifying govim directly in the plugin path? In any case it would be nice to document the recommended way to manually test `govim` while working on it.

**Comment by Vlad-Shevliakov** [comment]
**Maybe** you are right

**Comment by leitzler** [comment]
It's a really good idea, and I totally agree that it should be documented.

I don't know if my workflow is the ideal either, but maybe it can bring some new ideas. It is based on using plug as installer and I have the following as a part of my `.vimrc`:
```
if $GOVIM_DEV != ""
    " Probably want export GOVIM_ALWAYS_INSTALL=true as well
    Plug 'govim/govim', {'dir': $GOVIM_DEV}
else
    Plug 'govim/govim'
endif
```

That allows me to set env var `GOVIM_DEV` (_note that it is a self made up env var that isn't a part of govim_) to the folder that contain the govim repo that I currently work on.

I set `GOVIM_ALWAYS_INSTALL=true` to make sure that both `govim` and `gopls` (that `go.mod` in `govim` points to, i.e. can be a directory replace) is built each time.

I also sometimes use `GOVIM_LOGFILE_TMPL=%v` to set a static name on the logs, so that I don't have to run `GOVIMLogfilePaths` each time if I restart vim often to test things out.

**Comment by myitcv** [comment]
Thanks @findleyr @leitzler 

Either approach works, but FWIW I follow a very similar approach as @leitzler (but actually set `GOVIM_DEV=true` and have a pre-determined directory for my local `govim` dev tree)

I've jotted down a first cut of notes on this here:

https://github.com/govim/govim/wiki/Contributors#developing-govim-locally

Feedback/corrections/suggestions etc welcomed. Particularly from those people using Vim8 packages/Pathogen, where this is somewhat harder.

I'll leave this open for now as a place for people to add further comments/thoughts.

**Comment by findleyr** [comment]
Thanks, those are exactly the tips I was looking for!

I think that documentation is more than sufficient, so feel free to close this whenever you want.
