### ISSUE TITLE
cmd/govim: refactor following gopls CL 215742

### ISSUE THREAD

**Issue by myitcv** [govim/govim#761]
In https://go-review.googlesource.com/c/tools/+/215742, @findleyr completed a major refactor of the LSP server implementation, part of the groundwork for https://github.com/golang/go/issues/34111 ( 🎉)

However this CL landing caused our scheduled `gopls@master` build to fail:

https://github.com/govim/govim/actions/runs/35810855

Reason being, it exposes our use of internals of `golang.org/x/tools/internal/lsp` via:
 https://github.com/govim/govim/blob/5cfafa064bdcf507be105d943b149d68a0927508/_scripts/revendorToolsInternal.sh

Hence the `govim` build requiring a commit after CL215742 will break.

This is a tracker to refactor the `govim`

**Comment by findleyr** [comment]
Sorry, I didn't stop to think that this would break govim!

The refactoring ended up not being *that* huge, but I'm a bit concerned that there is more to come.  I'd be happy to fix govim, but can we wait a week to do this?

Note that there was a bug in cancellation fixed in this CL that only affected gopls testing, but may have affected govim: the cancellation ID was not being serialized correctly from the client side, so if you were using the canceller handler I'm not sure if cancellation would have propagated!

**Comment by myitcv** [comment]
Don't apologise! We're using internal stuff here. So it's our fault!

We can wait except that the master scheduled daily build in this repo will be broken until we do something

**Comment by findleyr** [comment]
Eh, it can't be a large breakage, so I'll look at it sometime today or Monday.

**Comment by myitcv** [comment]
Just to check you've seen #762?

**Comment by findleyr** [comment]
Ah, I had missed that. Thanks!

**Comment by myitcv** [comment]
If that looks roughly right we can get it merged
