### ISSUE TITLE
TestScripts/scenario_modfile/go_local_mod is invalid

### ISSUE THREAD

**Issue by heschik** [govim/govim#946]
gopls doesn't support setting the `-modfile` flag. Ideally we would detect and warn/ignore the flag, but currently it risks interfering with internal implementation details.

Specifically, `go_local_mod_is_invalid` tests for behavior we explicitly don't want: updates to a `go.mod` file without the user requesting them. The only reason it's happening is that the flag in `GOFLAGS` is being used instead of the one set by `gopls` while calculating quick fixes. I think the test should be deleted.

@stamblerre @findleyr

**Comment by myitcv** [comment]
> gopls doesn't support setting the -modfile flag

Is this documented anywhere? 

> Ideally we would detect and warn/ignore the flag, but currently it risks interfering with internal implementation details.

Agreed. 

> Specifically, go_local_mod_is_invalid tests for behavior we explicitly don't want: updates to a go.mod file without the user requesting them

I think we do need to continue to support a mode that users can opt into in which changes _are_ automatically applied to a user's `go.mod`. I completely agree with https://github.com/golang/go/issues/40728, but in the context of using my editor I am implicitly giving `gopls` permission to modify my `go.mod`. Otherwise, at least as far as I've understood it, a common workflow for me would end up becoming:

* accept unimported completion candidate
* run `go test` which now fails under https://github.com/golang/go/issues/40728
* have to manually accept change to `go.mod` because `gopls` is maintaining a shadow `go.mod` where the change has been made but the real `go.mod` is as yet unaltered (this is effectively a variant of the concern raised in  https://github.com/golang/go/issues/32394#issuecomment-689542541)

**Comment by heschik** [comment]
No, it's not documented. Very few people even know the flag exists, so documenting it is not high on my priority list.

With `TempModfile` enabled (the default) and Go 1.14+, gopls already doesn't update `go.mod` without user interaction. We may choose to change the behavior at some point due to golang/go#40728, but it still won't default to updating `go.mod`.

I think it's fine to want automatic `go.mod` updates, but this is not the way to accomplish that. For now, disabling `TempModfile` is reasonable. If this is a common request we can consider how to enable it more gracefully. Either way, setting `-modfile` is not an approach we can support.

**Comment by myitcv** [comment]
> I think it's fine to want automatic go.mod updates, but this is not the way to accomplish that

My point wasn't that we should use `-modfile` to achieve this, it was a response to your statement of what you do not want. 

I'll raise a `gopls` issue that encapsulates the mode/option I'm talking about.
